# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				ocelot = true
				horse = true
				vindicator = true
				ender_dragon = true
				evoker = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				chicken = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				blaze = true
				end_crystal = true
				endermite = true
				cat = true
				zombie = true
				ender_pearl = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				illusioner = true
				eye_of_ender = true
				villager = true
				wolf = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				polar_bear = true
				falling_block = true
				cave_spider = true
				cod = true
				witch = true
				spider = true
				husk = true
				giant = true
				goat = true
				guardian = true
				hoglin = true
				item_frame = true
				fireball = true
				leash_knot = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				command_block_minecart = true
				furnace_minecart = true
				hopper_minecart = true
				spawner_minecart = true
				tnt_minecart = true
				mule = true
				mooshroom = true
				painting = true
				panda = true
				phantom = true
				piglin = true
				piglin_brute = true
				tnt = true
				ravager = true
				shulker = true
				shulker_bullet = true
				silverfish = true
				skeleton_horse = true
				small_fireball = true
				snow_golem = true
				snowball = true
				spectral_arrow = true
				strider = true
				tadpole = true
				egg = true
				experience_bottle = true
				potion = true
				trident = true
				trader_llama = true
				vex = true
				wandering_trader = true
				warden = true
				wither = true
				wither_skeleton = true
				wither_skull = true
				zoglin = true
				zombie_horse = true
				zombified_piglin = true
				fishing_bobber = true

			[light_sources.settings.entities.naturalist]
				robin = true
				rattlesnake = true
				deer = true
				snail = true
				canary = true
				firefly = true
				bluejay = true
				butterfly = true
				coral_snake = true
				snake = true
				bear = true
				cardinal = true
				caterpillar = true

			[light_sources.settings.entities.biomemakeover]
				rootling = true
				cowboy = true
				lightning_bug = true
				scuttler = true
				owl = true
				lightning_bug_alternate = true
				helmit_crab = true
				decayed = true
				dragonfly = true
				ghost = true
				blightbat = true
				mushroom_trader = true
				lightning_bottle = true
				tumbleweed = true
				bm_boat = true
				bm_chest_boat = true
				glowfish = true
				toad = true
				tadpole = true
				moth = true
				adjudicator = true
				adjudicator_mimic = true
				stone_golem = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				camel = true
				penguin = true
				coconut_crab = true
				boat = true
				chest_boat = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true
				mauler = true
				iceologer = true
				ice_chunk = true

			[light_sources.settings.entities.goblintraders]
				goblin_trader = true
				vein_goblin_trader = true

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				furnace = true
				chest = true
				trapped_chest = true
				ender_chest = true
				jukebox = true
				dispenser = true
				dropper = true
				sign = true
				mob_spawner = true
				piston = true
				brewing_stand = true
				enchanting_table = true
				end_portal = true
				beacon = true
				skull = true
				daylight_detector = true
				hopper = true
				comparator = true
				banner = true
				structure_block = true
				end_gateway = true
				command_block = true
				shulker_box = true
				bed = true
				conduit = true
				barrel = true
				smoker = true
				blast_furnace = true
				lectern = true
				bell = true
				jigsaw = true
				campfire = true
				beehive = true
				sculk_sensor = true
				sculk_catalyst = true
				sculk_shrieker = true

			[light_sources.settings.block_entities.biomemakeover]
				poltergeist = true
				lightning_bug_bottle = true
				tapestry = true
				altar = true
				directional_data = true

			[light_sources.settings.block_entities.ecologics]
				sign = true
				pot = true

			[light_sources.settings.block_entities.fwaystones]
				waystone = true

